name: Build Qt Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        compiler: [msvc, gcc]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Qt
        if: matrix.os == 'ubuntu-latest'
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'linux'
          archives: 'qtbase qtdeclarative qttools'

      - name: Set up Qt
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          archives: 'qtbase qtdeclarative qttools'

      - name: Set QTDIR and QtToolsPath
        shell: bash
        run: |
          echo "QTDIR=$QT_ROOT_DIR" >> "$GITHUB_ENV"
          echo "QtToolsPath=$QT_ROOT_DIR/bin" >> "$GITHUB_ENV"

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
    
      - name: Configure MSVC environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    
      - name: Configure and Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          qmake -makefile
          make

          
      - name: Configure and Build
        if: matrix.os == 'windows-latest'
        run: |
            mkdir build
            cd build
            pwd
            qmake ../snake.pro -spec win32-msvc "CONFIG+=release"
            nmake

