name: Build Qt Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        compiler: [gcc]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Qt
        if: matrix.os == 'ubuntu-latest'
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'linux'
          archives: 'qtbase qtdeclarative qttools'

      - name: Set up Qt
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          archives: 'qtbase qtdeclarative qttools'

      - name: Set QTDIR and QtToolsPath
        shell: bash
        run: |
          echo "QTDIR=$QT_ROOT_DIR" >> "$GITHUB_ENV"
          echo "QtToolsPath=$QT_ROOT_DIR/bin" >> "$GITHUB_ENV"

      - name: Install GCC for Windows
        run: |
          curl -L -o mingw.zip https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download
          7z x mingw.zip -oC:/mingw --yes
          $env:PATH = "C:\mingw\mingw32\bin;$env:PATH"

      - name: Configure and Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          qmake -makefile
          make

          
      - name: Configure and Build
        if: matrix.os == 'windows-latest'
        run: |
            mkdir build
            cd build
            pwd
            qmake ../snake.pro -spec win32-msvc "CONFIG+=release"
            ming32-make

