name: Build Qt Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          archives: 'qtbase qtdeclarative qttools'
          arch: 'win64_mingw81'

      - name: Configure and Build
        run: |
            mkdir build
            cd build
            pwd
            qmake ../snake.pro
            mingw32-make
      - name: Deploy DLLs
        run: |
          cd build/release
          windeployqt --release --no-translations --no-angle --no-opengl-sw Snake.exe
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: Snake
            path: build/release/Snake.exe